import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#6bffc1",
        "on-secondary": "#7c0953",
        "tertiary-fixed": "#6bffc1",
        "inverse-on-surface": "#4d556b",
        "surface-container-low": "#081329",
        secondary: "#ffafd3",
        "on-background": "#dee5ff",
        "surface-container-high": "#101e3e",
        "on-secondary-container": "#fa77bb",
        "error-container": "#8a1632",
        tertiary: "#cdffe3",
        "on-primary": "#004f69",
        background: "#060e20",
        "surface-bright": "#172b54",
        "on-error": "#490013",
        "surface-dim": "#060e20",
        "on-tertiary": "#006948",
        "inverse-primary": "#006787",
        "on-surface": "#dee5ff",
        error: "#fd6f85",
        "on-secondary-fixed-variant": "#a02d70",
        "on-error-container": "#ff97a3",
        "on-tertiary-fixed": "#004b33",
        "inverse-surface": "#faf8ff",
        "on-tertiary-container": "#006042",
        "on-primary-fixed": "#003041",
        "on-secondary-fixed": "#7b0852",
        "tertiary-fixed-dim": "#5af0b4",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#142449",
        "primary-dim": "#6cc3eb",
        outline: "#65759e",
        "surface-tint": "#9bddff",
        "tertiary-dim": "#5af0b4",
        "secondary-dim": "#f673b7",
        "secondary-fixed": "#ffd8e7",
        "primary-fixed-dim": "#6cc3eb",
        primary: "#9bddff",
        "secondary-fixed-dim": "#ffc4dd",
        "outline-variant": "#38476d",
        "error-dim": "#c8475d",
        "surface-container": "#0c1934",
        "on-tertiary-fixed-variant": "#006b4a",
        "primary-fixed": "#7bd1fa",
        "on-surface-variant": "#9baad6",
        "secondary-container": "#4f0033",
        "primary-container": "#7bd1fa",
        surface: "#060e20",
        "surface-variant": "#142449",
        "on-primary-fixed-variant": "#004f69",
        "on-primary-container": "#00465d",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
